table dim_date
	lineageTag: bb203f38-a1a4-4e83-85fc-e801996e7494

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 7ee30b87-a7f1-4235-a18c-25a2310ccd12
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cdae5b07-6f82-430a-a8b2-a675db158247
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 57c1de7b-6133-451d-9132-ff8e351ecd07
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: fcf83f01-79cd-49a6-8a8c-2437b8f8f43c
		summarizeBy: none
		sourceColumn: month_num

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: 87ab443c-740b-41a5-a4d2-ce67d21f4953
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: e3a0e5f2-2faa-4ac2-a414-d8b5d7f23dcd
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column week_day
		dataType: int64
		formatString: 0
		lineageTag: e6c73876-9005-4424-a0b2-f5a2e933b2b7
		summarizeBy: none
		sourceColumn: week_day

		annotation SummarizationSetBy = Automatic

	column week_day_name
		dataType: string
		lineageTag: be65f8b3-7b40-40c6-968c-6a3bf7c8ba88
		summarizeBy: none
		sourceColumn: week_day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 4f3d8029-479b-4f3c-bbe4-7f15cd5c6236
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column week_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: cadf7c00-e7ec-4a43-9efb-7daaf9d60bf9
		summarizeBy: none
		sourceColumn: week_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column iso_week_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1b54762-fcb5-49a9-8676-e502474844ad
		summarizeBy: none
		sourceColumn: iso_week_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_date = m
		mode: import
		queryGroup: 'sales_pipeline dimensions'
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "common_db", [ReturnSingleDatabase=true]),
				    sales_pipeline_dim_date = Source{[Schema="common_db",Item="dim_date"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(sales_pipeline_dim_date, each Date.IsInPreviousNYears([date], 2) or Date.IsInCurrentYear([date]))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

