table dim_date
	lineageTag: bb203f38-a1a4-4e83-85fc-e801996e7494
	dataCategory: Time

	/// Integer surrogate key uniquely identifying each date (format YYYYMMDD). Primary key for this table.
	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 1f281470-2486-4c02-87f0-9b234ae974d4
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	/// Full calendar date value.
	column Date
		dataType: dateTime
		isKey
		formatString: MM/DD/YY
		lineageTag: 7c60def9-d131-436a-b128-ca4bf1148914
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	/// Calendar year number (e.g., 2024).
	column Year
		dataType: int64
		formatString: 0
		lineageTag: e1a6e524-cac6-48d1-87c2-56cdb168615b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// Numeric month of the year (1=January through 12=December).
	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: f657ca29-e279-46da-bf76-9061cd06cc4e
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	/// Full month name (e.g., January, February).
	column Month
		dataType: string
		lineageTag: 3ddc68a7-3f1c-4a5a-8cde-d53aea42bcbb
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	/// Calendar quarter number (1 through 4).
	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: db5988b8-b679-4976-bbe7-d1533fcba8e9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	/// Numeric day of the week (1=Sunday through 7=Saturday).
	column WeekDay
		dataType: int64
		formatString: 0
		lineageTag: 2f265bfa-21d4-4c3f-979b-60ea28732e68
		summarizeBy: none
		sourceColumn: WeekDay

		annotation SummarizationSetBy = Automatic

	/// Full name of the day of the week (e.g., Monday, Tuesday).
	column WeekDayName
		dataType: string
		lineageTag: 3be9edd3-b6d0-4f35-80fc-e7dad33842cf
		summarizeBy: none
		sourceColumn: WeekDayName

		annotation SummarizationSetBy = Automatic

	/// Flag indicating whether the date falls on a weekend (1=Yes, 0=No).
	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: e9377951-5439-4399-a9b6-870840acec56
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	/// Date of the first day (Sunday) of the week containing this date.
	column WeekStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb5820af-0b97-4678-b0ee-4446ac9de720
		summarizeBy: none
		sourceColumn: WeekStart

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// ISO 8601 week start date (Monday) of the week containing this date.
	column ISOWeekStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f7fd45b-43df-4e5e-943b-90e376ca762a
		summarizeBy: none
		sourceColumn: ISOWeekStart

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_date = m
		mode: import
		queryGroup: 'sales_pipeline dimensions'
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "sales_pipeline", [ReturnSingleDatabase=true]),
				    sales_pipeline_dim_date = Source{[Schema="sales_pipeline",Item="dim_date"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(sales_pipeline_dim_date, each Date.IsInPreviousNYears([Date], 2) or Date.IsInCurrentYear([Date]))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

